version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - CORS_ORIGIN=http://localhost:3000
      - API_URL=http://localhost:5001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/users_db
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRES_IN=24h
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 